FROM feedme-tech-test:base

COPY ./consumer ./consumer

WORKDIR consumer

RUN npm ci

ENV LOG_LEVEL=warn

ENV NOSQL_CONNECTION_STRING=mongodb://mongo:27017
ENV NOSQL_DB_NAME=FeedMe

ENV RABBITMQ_URL=amqp://rabbitmq:rabbitmq@rabbitmq/feedme
ENV JSON_MESSAGE_QUEUE=FeedMeQueue

CMD ["npm", "run", "prod"]
